name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  application-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    
    - name: Build_DB
      run: docker-compose build
      
    - name: Inicialize_DB
      run: docker-compose up -d

    - name: Test
      run: go test -v main_test.go

  build-application:
    needs: application-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
  
    - name: Build
      run: go build -v main.go
